#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:11:16 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Cookables_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    Cookables_support.set_Tk_var()
    top = Cookables (root)
    Cookables_support.init(root, top)
    root.mainloop()

w = None
def create_Cookables(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Cookables(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Cookables_support.set_Tk_var()
    top = Cookables (w)
    Cookables_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Cookables():
    global w
    w.destroy()
    w = None

class Cookables:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x400+783+200")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1, 1)
        top.title("Cookables")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.SnackTopPic = tk.Button(top)
        self.SnackTopPic.place(relx=0.0, rely=0.0, height=100, width=200)
        self.SnackTopPic.configure(activebackground="#ececec")
        self.SnackTopPic.configure(activeforeground="#000000")
        self.SnackTopPic.configure(background="#d9d9d9")
        self.SnackTopPic.configure(disabledforeground="#a3a3a3")
        self.SnackTopPic.configure(foreground="#000000")
        self.SnackTopPic.configure(highlightbackground="#d9d9d9")
        self.SnackTopPic.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"Example.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.SnackTopPic.configure(image=_img0)
        self.SnackTopPic.configure(overrelief="raised")
        self.SnackTopPic.configure(pady="0")

        self.MainTopPic = tk.Button(top)
        self.MainTopPic.place(relx=0.333, rely=0.0, height=100, width=200)
        self.MainTopPic.configure(activebackground="#ececec")
        self.MainTopPic.configure(activeforeground="#000000")
        self.MainTopPic.configure(background="#d9d9d9")
        self.MainTopPic.configure(disabledforeground="#a3a3a3")
        self.MainTopPic.configure(foreground="#000000")
        self.MainTopPic.configure(highlightbackground="#d9d9d9")
        self.MainTopPic.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"../Users/AlexW/Desktop/Example.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.MainTopPic.configure(image=_img1)
        self.MainTopPic.configure(pady="0")

        self.DessertTopPic = tk.Button(top)
        self.DessertTopPic.place(relx=0.667, rely=0.0, height=100, width=200)
        self.DessertTopPic.configure(activebackground="#ececec")
        self.DessertTopPic.configure(activeforeground="#000000")
        self.DessertTopPic.configure(background="#d9d9d9")
        self.DessertTopPic.configure(disabledforeground="#a3a3a3")
        self.DessertTopPic.configure(foreground="#000000")
        self.DessertTopPic.configure(highlightbackground="#d9d9d9")
        self.DessertTopPic.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"../Users/AlexW/Desktop/Example.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.DessertTopPic.configure(image=_img2)
        self.DessertTopPic.configure(pady="0")

        self.CookablesSnack = tk.Label(top)
        self.CookablesSnack.place(relx=0.0, rely=0.25, height=25, width=200)
        self.CookablesSnack.configure(activebackground="#f9f9f9")
        self.CookablesSnack.configure(activeforeground="black")
        self.CookablesSnack.configure(background="#3080cf")
        self.CookablesSnack.configure(disabledforeground="#a3a3a3")
        self.CookablesSnack.configure(foreground="#000000")
        self.CookablesSnack.configure(highlightbackground="#d9d9d9")
        self.CookablesSnack.configure(highlightcolor="black")
        self.CookablesSnack.configure(relief="raised")
        self.CookablesSnack.configure(textvariable=Cookables_support.snacknamevar)

        self.CookablesSnackList = tk.Label(top)
        self.CookablesSnackList.place(relx=0.0, rely=0.313, height=275
                , width=200)
        self.CookablesSnackList.configure(activebackground="#f9f9f9")
        self.CookablesSnackList.configure(activeforeground="black")
        self.CookablesSnackList.configure(background="#bad5ef")
        self.CookablesSnackList.configure(disabledforeground="#a3a3a3")
        self.CookablesSnackList.configure(foreground="#000000")
        self.CookablesSnackList.configure(highlightbackground="#d9d9d9")
        self.CookablesSnackList.configure(highlightcolor="black")
        self.CookablesSnackList.configure(relief="raised")
        self.CookablesSnackList.configure(textvariable=Cookables_support.cookablessnacklistvar)

        self.CookablesMainList = tk.Label(top)
        self.CookablesMainList.place(relx=0.333, rely=0.313, height=275
                , width=200)
        self.CookablesMainList.configure(activebackground="#f9f9f9")
        self.CookablesMainList.configure(activeforeground="black")
        self.CookablesMainList.configure(background="#d5efba")
        self.CookablesMainList.configure(disabledforeground="#a3a3a3")
        self.CookablesMainList.configure(foreground="#000000")
        self.CookablesMainList.configure(highlightbackground="#d9d9d9")
        self.CookablesMainList.configure(highlightcolor="black")
        self.CookablesMainList.configure(relief="raised")
        self.CookablesMainList.configure(textvariable=Cookables_support.cookablesmainlistvar)

        self.CookablesDessertList = tk.Label(top)
        self.CookablesDessertList.place(relx=0.667, rely=0.313, height=275
                , width=200)
        self.CookablesDessertList.configure(activebackground="#f9f9f9")
        self.CookablesDessertList.configure(activeforeground="black")
        self.CookablesDessertList.configure(background="#fcf2ad")
        self.CookablesDessertList.configure(disabledforeground="#a3a3a3")
        self.CookablesDessertList.configure(foreground="#000000")
        self.CookablesDessertList.configure(highlightbackground="#d9d9d9")
        self.CookablesDessertList.configure(highlightcolor="black")
        self.CookablesDessertList.configure(relief="raised")
        self.CookablesDessertList.configure(textvariable=Cookables_support.cookablesdessertlistvar)

        self.CookablesMain = tk.Label(top)
        self.CookablesMain.place(relx=0.333, rely=0.25, height=25, width=200)
        self.CookablesMain.configure(activebackground="#f9f9f9")
        self.CookablesMain.configure(activeforeground="black")
        self.CookablesMain.configure(background="#80cf30")
        self.CookablesMain.configure(disabledforeground="#a3a3a3")
        self.CookablesMain.configure(foreground="#000000")
        self.CookablesMain.configure(highlightbackground="#d9d9d9")
        self.CookablesMain.configure(highlightcolor="black")
        self.CookablesMain.configure(relief="raised")
        self.CookablesMain.configure(textvariable=Cookables_support.mainnamevar)

        self.CookablesDessert = tk.Label(top)
        self.CookablesDessert.place(relx=0.667, rely=0.25, height=25, width=200)
        self.CookablesDessert.configure(activebackground="#f9f9f9")
        self.CookablesDessert.configure(activeforeground="black")
        self.CookablesDessert.configure(background="#eacf15")
        self.CookablesDessert.configure(disabledforeground="#a3a3a3")
        self.CookablesDessert.configure(foreground="#000000")
        self.CookablesDessert.configure(highlightbackground="#d9d9d9")
        self.CookablesDessert.configure(highlightcolor="black")
        self.CookablesDessert.configure(relief="raised")
        self.CookablesDessert.configure(textvariable=Cookables_support.dessertnamevar)

if __name__ == '__main__':
    vp_start_gui()





