#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:11:21 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global snacknamevar
    snacknamevar = tk.StringVar()
    snacknamevar.set('')
    global cookablessnacklistvar
    cookablessnacklistvar = tk.StringVar()
    cookablessnacklistvar.set('')
    global cookablesmainlistvar
    cookablesmainlistvar = tk.StringVar()
    cookablesmainlistvar.set('')
    global cookablesdessertlistvar
    cookablesdessertlistvar = tk.StringVar()
    cookablesdessertlistvar.set('')
    global mainnamevar
    mainnamevar = tk.StringVar()
    mainnamevar.set('')
    global dessertnamevar
    dessertnamevar = tk.StringVar()
    dessertnamevar.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Cookables
    Cookables.vp_start_gui()




