#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:14:03 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import CurrentMain_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    CurrentMain_support.set_Tk_var()
    top = CurrentMain (root)
    CurrentMain_support.init(root, top)
    root.mainloop()

w = None
def create_CurrentMain(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_CurrentMain(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    CurrentMain_support.set_Tk_var()
    top = CurrentMain (w)
    CurrentMain_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_CurrentMain():
    global w
    w.destroy()
    w = None

class CurrentMain:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x400+920+270")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1, 1)
        top.title("CurrentMain")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.CurrentMainTopPic = tk.Button(top)
        self.CurrentMainTopPic.place(relx=0.0, rely=0.0, height=100, width=200)
        self.CurrentMainTopPic.configure(activebackground="#ececec")
        self.CurrentMainTopPic.configure(activeforeground="#000000")
        self.CurrentMainTopPic.configure(background="#d9d9d9")
        self.CurrentMainTopPic.configure(disabledforeground="#a3a3a3")
        self.CurrentMainTopPic.configure(foreground="#000000")
        self.CurrentMainTopPic.configure(highlightbackground="#d9d9d9")
        self.CurrentMainTopPic.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"Example.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.CurrentMainTopPic.configure(image=_img0)
        self.CurrentMainTopPic.configure(overrelief="raised")
        self.CurrentMainTopPic.configure(pady="0")
        self.CurrentMainTopPic.configure(text='''CurrentMainTopPic''')

        self.CurrentMainName = tk.Label(top)
        self.CurrentMainName.place(relx=0.0, rely=0.25, height=25, width=200)
        self.CurrentMainName.configure(activebackground="#f9f9f9")
        self.CurrentMainName.configure(activeforeground="black")
        self.CurrentMainName.configure(background="#80cf30")
        self.CurrentMainName.configure(disabledforeground="#a3a3a3")
        self.CurrentMainName.configure(foreground="#000000")
        self.CurrentMainName.configure(highlightbackground="#d9d9d9")
        self.CurrentMainName.configure(highlightcolor="black")
        self.CurrentMainName.configure(relief="raised")
        self.CurrentMainName.configure(textvariable=CurrentMain_support.currentmainnamevar)

        self.CurrentMainList = tk.Label(top)
        self.CurrentMainList.place(relx=0.0, rely=0.313, height=275, width=200)
        self.CurrentMainList.configure(activebackground="#f9f9f9")
        self.CurrentMainList.configure(activeforeground="black")
        self.CurrentMainList.configure(background="#d5efba")
        self.CurrentMainList.configure(disabledforeground="#a3a3a3")
        self.CurrentMainList.configure(foreground="#000000")
        self.CurrentMainList.configure(highlightbackground="#d9d9d9")
        self.CurrentMainList.configure(highlightcolor="black")
        self.CurrentMainList.configure(relief="raised")
        self.CurrentMainList.configure(textvariable=CurrentMain_support.currentmainlistvar)

        self.StepCount1 = tk.Label(top)
        self.StepCount1.place(relx=0.333, rely=0.0, height=50, width=50)
        self.StepCount1.configure(activebackground="#f9f9f9")
        self.StepCount1.configure(activeforeground="black")
        self.StepCount1.configure(background="#808080")
        self.StepCount1.configure(disabledforeground="#a3a3a3")
        self.StepCount1.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount1.configure(foreground="#000000")
        self.StepCount1.configure(highlightbackground="#d9d9d9")
        self.StepCount1.configure(highlightcolor="black")
        self.StepCount1.configure(relief="raised")
        self.StepCount1.configure(text='''1''')

        self.StepCount2 = tk.Label(top)
        self.StepCount2.place(relx=0.333, rely=0.125, height=50, width=50)
        self.StepCount2.configure(activebackground="#f9f9f9")
        self.StepCount2.configure(activeforeground="black")
        self.StepCount2.configure(background="#949494")
        self.StepCount2.configure(disabledforeground="#a3a3a3")
        self.StepCount2.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount2.configure(foreground="#000000")
        self.StepCount2.configure(highlightbackground="#d9d9d9")
        self.StepCount2.configure(highlightcolor="black")
        self.StepCount2.configure(relief="raised")
        self.StepCount2.configure(text='''2''')

        self.StepCount3 = tk.Label(top)
        self.StepCount3.place(relx=0.333, rely=0.25, height=50, width=50)
        self.StepCount3.configure(activebackground="#f9f9f9")
        self.StepCount3.configure(activeforeground="black")
        self.StepCount3.configure(background="#808080")
        self.StepCount3.configure(disabledforeground="#a3a3a3")
        self.StepCount3.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount3.configure(foreground="#000000")
        self.StepCount3.configure(highlightbackground="#d9d9d9")
        self.StepCount3.configure(highlightcolor="black")
        self.StepCount3.configure(relief="raised")
        self.StepCount3.configure(text='''3''')

        self.StepCount4 = tk.Label(top)
        self.StepCount4.place(relx=0.333, rely=0.375, height=50, width=50)
        self.StepCount4.configure(activebackground="#f9f9f9")
        self.StepCount4.configure(activeforeground="black")
        self.StepCount4.configure(background="#949494")
        self.StepCount4.configure(disabledforeground="#a3a3a3")
        self.StepCount4.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount4.configure(foreground="#000000")
        self.StepCount4.configure(highlightbackground="#d9d9d9")
        self.StepCount4.configure(highlightcolor="black")
        self.StepCount4.configure(relief="raised")
        self.StepCount4.configure(text='''4''')

        self.StepCount5 = tk.Label(top)
        self.StepCount5.place(relx=0.333, rely=0.5, height=50, width=50)
        self.StepCount5.configure(activebackground="#f9f9f9")
        self.StepCount5.configure(activeforeground="black")
        self.StepCount5.configure(background="#808080")
        self.StepCount5.configure(disabledforeground="#a3a3a3")
        self.StepCount5.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount5.configure(foreground="#000000")
        self.StepCount5.configure(highlightbackground="#d9d9d9")
        self.StepCount5.configure(highlightcolor="black")
        self.StepCount5.configure(relief="raised")
        self.StepCount5.configure(text='''5''')

        self.StepCount6 = tk.Label(top)
        self.StepCount6.place(relx=0.333, rely=0.625, height=50, width=50)
        self.StepCount6.configure(activebackground="#f9f9f9")
        self.StepCount6.configure(activeforeground="black")
        self.StepCount6.configure(background="#949494")
        self.StepCount6.configure(disabledforeground="#a3a3a3")
        self.StepCount6.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount6.configure(foreground="#000000")
        self.StepCount6.configure(highlightbackground="#d9d9d9")
        self.StepCount6.configure(highlightcolor="black")
        self.StepCount6.configure(relief="raised")
        self.StepCount6.configure(text='''6''')

        self.StepCount7 = tk.Label(top)
        self.StepCount7.place(relx=0.333, rely=0.75, height=50, width=50)
        self.StepCount7.configure(activebackground="#f9f9f9")
        self.StepCount7.configure(activeforeground="black")
        self.StepCount7.configure(background="#808080")
        self.StepCount7.configure(disabledforeground="#a3a3a3")
        self.StepCount7.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount7.configure(foreground="#000000")
        self.StepCount7.configure(highlightbackground="#d9d9d9")
        self.StepCount7.configure(highlightcolor="black")
        self.StepCount7.configure(relief="raised")
        self.StepCount7.configure(text='''7''')

        self.StepCount8 = tk.Label(top)
        self.StepCount8.place(relx=0.333, rely=0.875, height=50, width=50)
        self.StepCount8.configure(activebackground="#f9f9f9")
        self.StepCount8.configure(activeforeground="black")
        self.StepCount8.configure(background="#949494")
        self.StepCount8.configure(disabledforeground="#a3a3a3")
        self.StepCount8.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount8.configure(foreground="#000000")
        self.StepCount8.configure(highlightbackground="#d9d9d9")
        self.StepCount8.configure(highlightcolor="black")
        self.StepCount8.configure(relief="raised")
        self.StepCount8.configure(text='''8''')

        self.MainStep1 = tk.Label(top)
        self.MainStep1.place(relx=0.417, rely=0.0, height=50, width=350)
        self.MainStep1.configure(activebackground="#f9f9f9")
        self.MainStep1.configure(activeforeground="black")
        self.MainStep1.configure(background="#c0c0c0")
        self.MainStep1.configure(disabledforeground="#a3a3a3")
        self.MainStep1.configure(foreground="#000000")
        self.MainStep1.configure(highlightbackground="#d9d9d9")
        self.MainStep1.configure(highlightcolor="black")
        self.MainStep1.configure(relief="raised")
        self.MainStep1.configure(textvariable=CurrentMain_support.mainstep1var)

        self.MainStep3 = tk.Label(top)
        self.MainStep3.place(relx=0.417, rely=0.25, height=50, width=350)
        self.MainStep3.configure(activebackground="#f9f9f9")
        self.MainStep3.configure(activeforeground="black")
        self.MainStep3.configure(background="#c0c0c0")
        self.MainStep3.configure(disabledforeground="#a3a3a3")
        self.MainStep3.configure(foreground="#000000")
        self.MainStep3.configure(highlightbackground="#d9d9d9")
        self.MainStep3.configure(highlightcolor="black")
        self.MainStep3.configure(relief="raised")
        self.MainStep3.configure(textvariable=CurrentMain_support.mainstep3var)

        self.MainStep5 = tk.Label(top)
        self.MainStep5.place(relx=0.417, rely=0.5, height=50, width=350)
        self.MainStep5.configure(activebackground="#f9f9f9")
        self.MainStep5.configure(activeforeground="black")
        self.MainStep5.configure(background="#c0c0c0")
        self.MainStep5.configure(disabledforeground="#a3a3a3")
        self.MainStep5.configure(foreground="#000000")
        self.MainStep5.configure(highlightbackground="#d9d9d9")
        self.MainStep5.configure(highlightcolor="black")
        self.MainStep5.configure(relief="raised")
        self.MainStep5.configure(textvariable=CurrentMain_support.mainstep5var)

        self.MainStep7 = tk.Label(top)
        self.MainStep7.place(relx=0.417, rely=0.75, height=50, width=350)
        self.MainStep7.configure(activebackground="#f9f9f9")
        self.MainStep7.configure(activeforeground="black")
        self.MainStep7.configure(background="#c0c0c0")
        self.MainStep7.configure(disabledforeground="#a3a3a3")
        self.MainStep7.configure(foreground="#000000")
        self.MainStep7.configure(highlightbackground="#d9d9d9")
        self.MainStep7.configure(highlightcolor="black")
        self.MainStep7.configure(relief="raised")
        self.MainStep7.configure(textvariable=CurrentMain_support.mainstep7var)

        self.MainStep2 = tk.Label(top)
        self.MainStep2.place(relx=0.417, rely=0.125, height=50, width=350)
        self.MainStep2.configure(activebackground="#f9f9f9")
        self.MainStep2.configure(activeforeground="black")
        self.MainStep2.configure(background="#d9d9d9")
        self.MainStep2.configure(disabledforeground="#a3a3a3")
        self.MainStep2.configure(foreground="#000000")
        self.MainStep2.configure(highlightbackground="#d9d9d9")
        self.MainStep2.configure(highlightcolor="black")
        self.MainStep2.configure(relief="raised")
        self.MainStep2.configure(textvariable=CurrentMain_support.mainstep2var)

        self.MainStep4 = tk.Label(top)
        self.MainStep4.place(relx=0.417, rely=0.375, height=50, width=350)
        self.MainStep4.configure(activebackground="#f9f9f9")
        self.MainStep4.configure(activeforeground="black")
        self.MainStep4.configure(background="#d9d9d9")
        self.MainStep4.configure(disabledforeground="#a3a3a3")
        self.MainStep4.configure(foreground="#000000")
        self.MainStep4.configure(highlightbackground="#d9d9d9")
        self.MainStep4.configure(highlightcolor="black")
        self.MainStep4.configure(relief="raised")
        self.MainStep4.configure(textvariable=CurrentMain_support.mainstep4var)

        self.MainStep6 = tk.Label(top)
        self.MainStep6.place(relx=0.417, rely=0.625, height=50, width=350)
        self.MainStep6.configure(activebackground="#f9f9f9")
        self.MainStep6.configure(activeforeground="black")
        self.MainStep6.configure(background="#d9d9d9")
        self.MainStep6.configure(disabledforeground="#a3a3a3")
        self.MainStep6.configure(foreground="#000000")
        self.MainStep6.configure(highlightbackground="#d9d9d9")
        self.MainStep6.configure(highlightcolor="black")
        self.MainStep6.configure(relief="raised")
        self.MainStep6.configure(textvariable=CurrentMain_support.mainstep6var)

        self.MainStep8 = tk.Label(top)
        self.MainStep8.place(relx=0.417, rely=0.875, height=50, width=350)
        self.MainStep8.configure(activebackground="#f9f9f9")
        self.MainStep8.configure(activeforeground="black")
        self.MainStep8.configure(background="#d9d9d9")
        self.MainStep8.configure(disabledforeground="#a3a3a3")
        self.MainStep8.configure(foreground="#000000")
        self.MainStep8.configure(highlightbackground="#d9d9d9")
        self.MainStep8.configure(highlightcolor="black")
        self.MainStep8.configure(relief="raised")
        self.MainStep8.configure(textvariable=CurrentMain_support.mainstep8var)

if __name__ == '__main__':
    vp_start_gui()





