#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:14:47 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import CurrentSnack_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    CurrentSnack_support.set_Tk_var()
    top = CurrentSnack (root)
    CurrentSnack_support.init(root, top)
    root.mainloop()

w = None
def create_CurrentSnack(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_CurrentSnack(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    CurrentSnack_support.set_Tk_var()
    top = CurrentSnack (w)
    CurrentSnack_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_CurrentSnack():
    global w
    w.destroy()
    w = None

class CurrentSnack:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x400+920+270")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1, 1)
        top.title("CurrentSnack")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.CurrentSnackTopPic = tk.Button(top)
        self.CurrentSnackTopPic.place(relx=0.0, rely=0.0, height=100, width=200)
        self.CurrentSnackTopPic.configure(activebackground="#ececec")
        self.CurrentSnackTopPic.configure(activeforeground="#000000")
        self.CurrentSnackTopPic.configure(background="#d9d9d9")
        self.CurrentSnackTopPic.configure(disabledforeground="#a3a3a3")
        self.CurrentSnackTopPic.configure(foreground="#000000")
        self.CurrentSnackTopPic.configure(highlightbackground="#d9d9d9")
        self.CurrentSnackTopPic.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"Example.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.CurrentSnackTopPic.configure(image=_img0)
        self.CurrentSnackTopPic.configure(overrelief="raised")
        self.CurrentSnackTopPic.configure(pady="0")
        self.CurrentSnackTopPic.configure(text='''CurrentSnackTopPic''')

        self.CurrentSnackName = tk.Label(top)
        self.CurrentSnackName.place(relx=0.0, rely=0.25, height=25, width=200)
        self.CurrentSnackName.configure(activebackground="#f9f9f9")
        self.CurrentSnackName.configure(activeforeground="black")
        self.CurrentSnackName.configure(background="#3080cf")
        self.CurrentSnackName.configure(disabledforeground="#a3a3a3")
        self.CurrentSnackName.configure(foreground="#000000")
        self.CurrentSnackName.configure(highlightbackground="#d9d9d9")
        self.CurrentSnackName.configure(highlightcolor="black")
        self.CurrentSnackName.configure(relief="raised")
        self.CurrentSnackName.configure(textvariable=CurrentSnack_support.currentsnacknamevar)

        self.CurrentSnackList = tk.Label(top)
        self.CurrentSnackList.place(relx=0.0, rely=0.313, height=275, width=200)
        self.CurrentSnackList.configure(activebackground="#f9f9f9")
        self.CurrentSnackList.configure(activeforeground="black")
        self.CurrentSnackList.configure(background="#bad5ef")
        self.CurrentSnackList.configure(disabledforeground="#a3a3a3")
        self.CurrentSnackList.configure(foreground="#000000")
        self.CurrentSnackList.configure(highlightbackground="#d9d9d9")
        self.CurrentSnackList.configure(highlightcolor="black")
        self.CurrentSnackList.configure(relief="raised")
        self.CurrentSnackList.configure(textvariable=CurrentSnack_support.currentsnacklistvar)

        self.StepCount1 = tk.Label(top)
        self.StepCount1.place(relx=0.333, rely=0.0, height=50, width=50)
        self.StepCount1.configure(activebackground="#f9f9f9")
        self.StepCount1.configure(activeforeground="black")
        self.StepCount1.configure(background="#808080")
        self.StepCount1.configure(disabledforeground="#a3a3a3")
        self.StepCount1.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount1.configure(foreground="#000000")
        self.StepCount1.configure(highlightbackground="#d9d9d9")
        self.StepCount1.configure(highlightcolor="black")
        self.StepCount1.configure(relief="raised")
        self.StepCount1.configure(text='''1''')

        self.StepCount2 = tk.Label(top)
        self.StepCount2.place(relx=0.333, rely=0.125, height=50, width=50)
        self.StepCount2.configure(activebackground="#f9f9f9")
        self.StepCount2.configure(activeforeground="black")
        self.StepCount2.configure(background="#949494")
        self.StepCount2.configure(disabledforeground="#a3a3a3")
        self.StepCount2.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount2.configure(foreground="#000000")
        self.StepCount2.configure(highlightbackground="#d9d9d9")
        self.StepCount2.configure(highlightcolor="black")
        self.StepCount2.configure(relief="raised")
        self.StepCount2.configure(text='''2''')

        self.StepCount3 = tk.Label(top)
        self.StepCount3.place(relx=0.333, rely=0.25, height=50, width=50)
        self.StepCount3.configure(activebackground="#f9f9f9")
        self.StepCount3.configure(activeforeground="black")
        self.StepCount3.configure(background="#808080")
        self.StepCount3.configure(disabledforeground="#a3a3a3")
        self.StepCount3.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount3.configure(foreground="#000000")
        self.StepCount3.configure(highlightbackground="#d9d9d9")
        self.StepCount3.configure(highlightcolor="black")
        self.StepCount3.configure(relief="raised")
        self.StepCount3.configure(text='''3''')

        self.StepCount4 = tk.Label(top)
        self.StepCount4.place(relx=0.333, rely=0.375, height=50, width=50)
        self.StepCount4.configure(activebackground="#f9f9f9")
        self.StepCount4.configure(activeforeground="black")
        self.StepCount4.configure(background="#949494")
        self.StepCount4.configure(disabledforeground="#a3a3a3")
        self.StepCount4.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount4.configure(foreground="#000000")
        self.StepCount4.configure(highlightbackground="#d9d9d9")
        self.StepCount4.configure(highlightcolor="black")
        self.StepCount4.configure(relief="raised")
        self.StepCount4.configure(text='''4''')

        self.StepCount5 = tk.Label(top)
        self.StepCount5.place(relx=0.333, rely=0.5, height=50, width=50)
        self.StepCount5.configure(activebackground="#f9f9f9")
        self.StepCount5.configure(activeforeground="black")
        self.StepCount5.configure(background="#808080")
        self.StepCount5.configure(disabledforeground="#a3a3a3")
        self.StepCount5.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount5.configure(foreground="#000000")
        self.StepCount5.configure(highlightbackground="#d9d9d9")
        self.StepCount5.configure(highlightcolor="black")
        self.StepCount5.configure(relief="raised")
        self.StepCount5.configure(text='''5''')

        self.StepCount6 = tk.Label(top)
        self.StepCount6.place(relx=0.333, rely=0.625, height=50, width=50)
        self.StepCount6.configure(activebackground="#f9f9f9")
        self.StepCount6.configure(activeforeground="black")
        self.StepCount6.configure(background="#949494")
        self.StepCount6.configure(disabledforeground="#a3a3a3")
        self.StepCount6.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount6.configure(foreground="#000000")
        self.StepCount6.configure(highlightbackground="#d9d9d9")
        self.StepCount6.configure(highlightcolor="black")
        self.StepCount6.configure(relief="raised")
        self.StepCount6.configure(text='''6''')

        self.StepCount7 = tk.Label(top)
        self.StepCount7.place(relx=0.333, rely=0.75, height=50, width=50)
        self.StepCount7.configure(activebackground="#f9f9f9")
        self.StepCount7.configure(activeforeground="black")
        self.StepCount7.configure(background="#808080")
        self.StepCount7.configure(disabledforeground="#a3a3a3")
        self.StepCount7.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount7.configure(foreground="#000000")
        self.StepCount7.configure(highlightbackground="#d9d9d9")
        self.StepCount7.configure(highlightcolor="black")
        self.StepCount7.configure(relief="raised")
        self.StepCount7.configure(text='''7''')

        self.StepCount8 = tk.Label(top)
        self.StepCount8.place(relx=0.333, rely=0.875, height=50, width=50)
        self.StepCount8.configure(activebackground="#f9f9f9")
        self.StepCount8.configure(activeforeground="black")
        self.StepCount8.configure(background="#949494")
        self.StepCount8.configure(disabledforeground="#a3a3a3")
        self.StepCount8.configure(font="-family ModMatrix -size 24 -weight bold -slant roman -underline 0 -overstrike 0")
        self.StepCount8.configure(foreground="#000000")
        self.StepCount8.configure(highlightbackground="#d9d9d9")
        self.StepCount8.configure(highlightcolor="black")
        self.StepCount8.configure(relief="raised")
        self.StepCount8.configure(text='''8''')

        self.SnackStep1 = tk.Label(top)
        self.SnackStep1.place(relx=0.417, rely=0.0, height=50, width=350)
        self.SnackStep1.configure(activebackground="#f9f9f9")
        self.SnackStep1.configure(activeforeground="black")
        self.SnackStep1.configure(background="#c0c0c0")
        self.SnackStep1.configure(disabledforeground="#a3a3a3")
        self.SnackStep1.configure(foreground="#000000")
        self.SnackStep1.configure(highlightbackground="#d9d9d9")
        self.SnackStep1.configure(highlightcolor="black")
        self.SnackStep1.configure(relief="raised")
        self.SnackStep1.configure(textvariable=CurrentSnack_support.snackstep1var)

        self.SnackStep3 = tk.Label(top)
        self.SnackStep3.place(relx=0.417, rely=0.25, height=50, width=350)
        self.SnackStep3.configure(activebackground="#f9f9f9")
        self.SnackStep3.configure(activeforeground="black")
        self.SnackStep3.configure(background="#c0c0c0")
        self.SnackStep3.configure(disabledforeground="#a3a3a3")
        self.SnackStep3.configure(foreground="#000000")
        self.SnackStep3.configure(highlightbackground="#d9d9d9")
        self.SnackStep3.configure(highlightcolor="black")
        self.SnackStep3.configure(relief="raised")
        self.SnackStep3.configure(textvariable=CurrentSnack_support.snackstep3var)

        self.SnackStep5 = tk.Label(top)
        self.SnackStep5.place(relx=0.417, rely=0.5, height=50, width=350)
        self.SnackStep5.configure(activebackground="#f9f9f9")
        self.SnackStep5.configure(activeforeground="black")
        self.SnackStep5.configure(background="#c0c0c0")
        self.SnackStep5.configure(disabledforeground="#a3a3a3")
        self.SnackStep5.configure(foreground="#000000")
        self.SnackStep5.configure(highlightbackground="#d9d9d9")
        self.SnackStep5.configure(highlightcolor="black")
        self.SnackStep5.configure(relief="raised")
        self.SnackStep5.configure(textvariable=CurrentSnack_support.snackstep5var)

        self.SnackStep7 = tk.Label(top)
        self.SnackStep7.place(relx=0.417, rely=0.75, height=50, width=350)
        self.SnackStep7.configure(activebackground="#f9f9f9")
        self.SnackStep7.configure(activeforeground="black")
        self.SnackStep7.configure(background="#c0c0c0")
        self.SnackStep7.configure(disabledforeground="#a3a3a3")
        self.SnackStep7.configure(foreground="#000000")
        self.SnackStep7.configure(highlightbackground="#d9d9d9")
        self.SnackStep7.configure(highlightcolor="black")
        self.SnackStep7.configure(relief="raised")
        self.SnackStep7.configure(textvariable=CurrentSnack_support.snackstep7var)

        self.SnackStep2 = tk.Label(top)
        self.SnackStep2.place(relx=0.417, rely=0.125, height=50, width=350)
        self.SnackStep2.configure(activebackground="#f9f9f9")
        self.SnackStep2.configure(activeforeground="black")
        self.SnackStep2.configure(background="#d9d9d9")
        self.SnackStep2.configure(disabledforeground="#a3a3a3")
        self.SnackStep2.configure(foreground="#000000")
        self.SnackStep2.configure(highlightbackground="#d9d9d9")
        self.SnackStep2.configure(highlightcolor="black")
        self.SnackStep2.configure(relief="raised")
        self.SnackStep2.configure(textvariable=CurrentSnack_support.snackstep2var)

        self.SnackStep4 = tk.Label(top)
        self.SnackStep4.place(relx=0.417, rely=0.375, height=50, width=350)
        self.SnackStep4.configure(activebackground="#f9f9f9")
        self.SnackStep4.configure(activeforeground="black")
        self.SnackStep4.configure(background="#d9d9d9")
        self.SnackStep4.configure(disabledforeground="#a3a3a3")
        self.SnackStep4.configure(foreground="#000000")
        self.SnackStep4.configure(highlightbackground="#d9d9d9")
        self.SnackStep4.configure(highlightcolor="black")
        self.SnackStep4.configure(relief="raised")
        self.SnackStep4.configure(textvariable=CurrentSnack_support.snackstep4var)

        self.SnackStep6 = tk.Label(top)
        self.SnackStep6.place(relx=0.417, rely=0.625, height=50, width=350)
        self.SnackStep6.configure(activebackground="#f9f9f9")
        self.SnackStep6.configure(activeforeground="black")
        self.SnackStep6.configure(background="#d9d9d9")
        self.SnackStep6.configure(disabledforeground="#a3a3a3")
        self.SnackStep6.configure(foreground="#000000")
        self.SnackStep6.configure(highlightbackground="#d9d9d9")
        self.SnackStep6.configure(highlightcolor="black")
        self.SnackStep6.configure(relief="raised")
        self.SnackStep6.configure(textvariable=CurrentSnack_support.snackstep6var)

        self.SnackStep8 = tk.Label(top)
        self.SnackStep8.place(relx=0.417, rely=0.875, height=50, width=350)
        self.SnackStep8.configure(activebackground="#f9f9f9")
        self.SnackStep8.configure(activeforeground="black")
        self.SnackStep8.configure(background="#d9d9d9")
        self.SnackStep8.configure(disabledforeground="#a3a3a3")
        self.SnackStep8.configure(foreground="#000000")
        self.SnackStep8.configure(highlightbackground="#d9d9d9")
        self.SnackStep8.configure(highlightcolor="black")
        self.SnackStep8.configure(relief="raised")
        self.SnackStep8.configure(textvariable=CurrentSnack_support.snackstep8var)

if __name__ == '__main__':
    vp_start_gui()





