#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:14:50 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global currentsnacknamevar
    currentsnacknamevar = tk.StringVar()
    currentsnacknamevar.set('')
    global currentsnacklistvar
    currentsnacklistvar = tk.StringVar()
    currentsnacklistvar.set('')
    global snackstep1var
    snackstep1var = tk.StringVar()
    snackstep1var.set('')
    global snackstep3var
    snackstep3var = tk.StringVar()
    snackstep3var.set('')
    global snackstep5var
    snackstep5var = tk.StringVar()
    snackstep5var.set('')
    global snackstep7var
    snackstep7var = tk.StringVar()
    snackstep7var.set('')
    global snackstep2var
    snackstep2var = tk.StringVar()
    snackstep2var.set('')
    global snackstep4var
    snackstep4var = tk.StringVar()
    snackstep4var.set('')
    global snackstep6var
    snackstep6var = tk.StringVar()
    snackstep6var.set('')
    global snackstep8var
    snackstep8var = tk.StringVar()
    snackstep8var.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import CurrentSnack
    CurrentSnack.vp_start_gui()




