#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:17:14 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global mainnamevar1
    mainnamevar1 = tk.StringVar()
    mainnamevar1.set('')
    global mainlistvar1
    mainlistvar1 = tk.StringVar()
    mainlistvar1.set('')
    global mainlistvar2
    mainlistvar2 = tk.StringVar()
    mainlistvar2.set('')
    global mainlistvar3
    mainlistvar3 = tk.StringVar()
    mainlistvar3.set('')
    global mainnamevar2
    mainnamevar2 = tk.StringVar()
    mainnamevar2.set('')
    global mainnamevar3
    mainnamevar3 = tk.StringVar()
    mainnamevar3.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import RecipesMain
    RecipesMain.vp_start_gui()




