#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:16:51 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import RecipesDessert_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    RecipesDessert_support.set_Tk_var()
    top = RecipesSnack (root)
    RecipesDessert_support.init(root, top)
    root.mainloop()

w = None
def create_RecipesSnack(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_RecipesSnack(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    RecipesDessert_support.set_Tk_var()
    top = RecipesSnack (w)
    RecipesDessert_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_RecipesSnack():
    global w
    w.destroy()
    w = None

class RecipesSnack:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x400+783+200")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1, 1)
        top.title("RecipesSnack")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.DessertTopPic1 = tk.Button(top)
        self.DessertTopPic1.place(relx=0.0, rely=0.0, height=100, width=200)
        self.DessertTopPic1.configure(activebackground="#ececec")
        self.DessertTopPic1.configure(activeforeground="#000000")
        self.DessertTopPic1.configure(background="#d9d9d9")
        self.DessertTopPic1.configure(disabledforeground="#a3a3a3")
        self.DessertTopPic1.configure(foreground="#000000")
        self.DessertTopPic1.configure(highlightbackground="#d9d9d9")
        self.DessertTopPic1.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"Example.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.DessertTopPic1.configure(image=_img0)
        self.DessertTopPic1.configure(overrelief="raised")
        self.DessertTopPic1.configure(pady="0")

        self.DessertTopPic2 = tk.Button(top)
        self.DessertTopPic2.place(relx=0.333, rely=0.0, height=100, width=200)
        self.DessertTopPic2.configure(activebackground="#ececec")
        self.DessertTopPic2.configure(activeforeground="#000000")
        self.DessertTopPic2.configure(background="#d9d9d9")
        self.DessertTopPic2.configure(disabledforeground="#a3a3a3")
        self.DessertTopPic2.configure(foreground="#000000")
        self.DessertTopPic2.configure(highlightbackground="#d9d9d9")
        self.DessertTopPic2.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"../Users/AlexW/Desktop/Example.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.DessertTopPic2.configure(image=_img1)
        self.DessertTopPic2.configure(pady="0")

        self.DessertTopPic3 = tk.Button(top)
        self.DessertTopPic3.place(relx=0.667, rely=0.0, height=100, width=200)
        self.DessertTopPic3.configure(activebackground="#ececec")
        self.DessertTopPic3.configure(activeforeground="#000000")
        self.DessertTopPic3.configure(background="#d9d9d9")
        self.DessertTopPic3.configure(disabledforeground="#a3a3a3")
        self.DessertTopPic3.configure(foreground="#000000")
        self.DessertTopPic3.configure(highlightbackground="#d9d9d9")
        self.DessertTopPic3.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"../Users/AlexW/Desktop/Example.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.DessertTopPic3.configure(image=_img2)
        self.DessertTopPic3.configure(pady="0")

        self.RecipesDessert1 = tk.Label(top)
        self.RecipesDessert1.place(relx=0.0, rely=0.25, height=25, width=200)
        self.RecipesDessert1.configure(activebackground="#f9f9f9")
        self.RecipesDessert1.configure(activeforeground="black")
        self.RecipesDessert1.configure(background="#eacf15")
        self.RecipesDessert1.configure(disabledforeground="#a3a3a3")
        self.RecipesDessert1.configure(foreground="#000000")
        self.RecipesDessert1.configure(highlightbackground="#d9d9d9")
        self.RecipesDessert1.configure(highlightcolor="black")
        self.RecipesDessert1.configure(relief="raised")
        self.RecipesDessert1.configure(textvariable=RecipesDessert_support.dessertnamevar1)

        self.RecipesDessertList1 = tk.Label(top)
        self.RecipesDessertList1.place(relx=0.0, rely=0.313, height=275
                , width=200)
        self.RecipesDessertList1.configure(activebackground="#f9f9f9")
        self.RecipesDessertList1.configure(activeforeground="black")
        self.RecipesDessertList1.configure(background="#fcf2ad")
        self.RecipesDessertList1.configure(disabledforeground="#a3a3a3")
        self.RecipesDessertList1.configure(foreground="#000000")
        self.RecipesDessertList1.configure(highlightbackground="#d9d9d9")
        self.RecipesDessertList1.configure(highlightcolor="black")
        self.RecipesDessertList1.configure(relief="raised")
        self.RecipesDessertList1.configure(textvariable=RecipesDessert_support.dessertlistvar1)

        self.RecipesDessertList2 = tk.Label(top)
        self.RecipesDessertList2.place(relx=0.333, rely=0.313, height=275
                , width=200)
        self.RecipesDessertList2.configure(activebackground="#f9f9f9")
        self.RecipesDessertList2.configure(activeforeground="black")
        self.RecipesDessertList2.configure(background="#fcf2ad")
        self.RecipesDessertList2.configure(disabledforeground="#a3a3a3")
        self.RecipesDessertList2.configure(foreground="#000000")
        self.RecipesDessertList2.configure(highlightbackground="#d9d9d9")
        self.RecipesDessertList2.configure(highlightcolor="black")
        self.RecipesDessertList2.configure(relief="raised")
        self.RecipesDessertList2.configure(textvariable=RecipesDessert_support.dessertlistvar2)

        self.RecipesDessertList3 = tk.Label(top)
        self.RecipesDessertList3.place(relx=0.667, rely=0.313, height=275
                , width=200)
        self.RecipesDessertList3.configure(activebackground="#f9f9f9")
        self.RecipesDessertList3.configure(activeforeground="black")
        self.RecipesDessertList3.configure(background="#fcf2ad")
        self.RecipesDessertList3.configure(disabledforeground="#a3a3a3")
        self.RecipesDessertList3.configure(foreground="#000000")
        self.RecipesDessertList3.configure(highlightbackground="#d9d9d9")
        self.RecipesDessertList3.configure(highlightcolor="black")
        self.RecipesDessertList3.configure(relief="raised")
        self.RecipesDessertList3.configure(textvariable=RecipesDessert_support.dessertlistvar3)

        self.RecipesDessert2 = tk.Label(top)
        self.RecipesDessert2.place(relx=0.333, rely=0.25, height=25, width=200)
        self.RecipesDessert2.configure(activebackground="#f9f9f9")
        self.RecipesDessert2.configure(activeforeground="black")
        self.RecipesDessert2.configure(background="#eacf15")
        self.RecipesDessert2.configure(disabledforeground="#a3a3a3")
        self.RecipesDessert2.configure(foreground="#000000")
        self.RecipesDessert2.configure(highlightbackground="#d9d9d9")
        self.RecipesDessert2.configure(highlightcolor="black")
        self.RecipesDessert2.configure(relief="raised")
        self.RecipesDessert2.configure(textvariable=RecipesDessert_support.dessertnamevar2)

        self.RecipesDessert3 = tk.Label(top)
        self.RecipesDessert3.place(relx=0.667, rely=0.25, height=25, width=200)
        self.RecipesDessert3.configure(activebackground="#f9f9f9")
        self.RecipesDessert3.configure(activeforeground="black")
        self.RecipesDessert3.configure(background="#eacf15")
        self.RecipesDessert3.configure(disabledforeground="#a3a3a3")
        self.RecipesDessert3.configure(foreground="#000000")
        self.RecipesDessert3.configure(highlightbackground="#d9d9d9")
        self.RecipesDessert3.configure(highlightcolor="black")
        self.RecipesDessert3.configure(relief="raised")
        self.RecipesDessert3.configure(textvariable=RecipesDessert_support.dessertnamevar3)

if __name__ == '__main__':
    vp_start_gui()





