#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:16:54 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global dessertnamevar1
    dessertnamevar1 = tk.StringVar()
    dessertnamevar1.set('')
    global dessertlistvar1
    dessertlistvar1 = tk.StringVar()
    dessertlistvar1.set('')
    global dessertlistvar2
    dessertlistvar2 = tk.StringVar()
    dessertlistvar2.set('')
    global dessertlistvar3
    dessertlistvar3 = tk.StringVar()
    dessertlistvar3.set('')
    global dessertnamevar2
    dessertnamevar2 = tk.StringVar()
    dessertnamevar2.set('')
    global dessertnamevar3
    dessertnamevar3 = tk.StringVar()
    dessertnamevar3.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import RecipesDessert
    RecipesDessert.vp_start_gui()




