#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 27, 2020 09:17:31 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global snacknamevar1
    snacknamevar1 = tk.StringVar()
    snacknamevar1.set('')
    global snacklistvar1
    snacklistvar1 = tk.StringVar()
    snacklistvar1.set('')
    global snacklistvar2
    snacklistvar2 = tk.StringVar()
    snacklistvar2.set('')
    global snacklistvar3
    snacklistvar3 = tk.StringVar()
    snacklistvar3.set('')
    global snacknamevar2
    snacknamevar2 = tk.StringVar()
    snacknamevar2.set('')
    global snacknamevar3
    snacknamevar3 = tk.StringVar()
    snacknamevar3.set('')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import RecipesSnack
    RecipesSnack.vp_start_gui()




